version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/core"
      - "/language-server"
      - "/docs"
    schedule:
      interval: "daily"
    
    groups:
      monorepo-dependencies:
        patterns:
          - "*"
        group-by: dependency-name
