name: Run on itself

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run on itself
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: node scripts/run-on-itself.mjs
        continue-on-error: true