name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false # Prevents any OS failure from cancelling runs on other OSes
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 21
          - 22
          - 24
        folder:
          - Layers
          - Plugins
          - Functions
          - Framework-Lab
          - Recovery
          - Security
          - Language-Server

    name: Test ${{ matrix.folder }} (${{ matrix.os }}, Node ${{ matrix.node-version }})
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Build Language Server (if required)
        if: matrix.folder == 'Language-Server' || matrix.folder == 'language-server'
        run: npm run build

      - name: Run Tests with Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 2
          command: npm run test ${{ matrix.folder }}/